(4-1)日付の表示方法を変更しました
koda-momo-old/ex-vue-emp-manage-bugfix pull request #7
Opened 2021-11-17 04:47 UTC by koda-momo

変更場所：
・従業員一覧画面
・従業員詳細画面
2か所訂正しました。
fixHireDayという変数名(getter名)に自信が無いです。
もしもっと良い命名があればご教示頂けると幸いです。
宜しくお願いします。

2021-11-17 09:50 UTC, igamasayuki requested changes
気になる点をコメントしました。
差し戻しますので、再度pushして管理シートより再レビュー依頼をしてください。
(この場合、push後、再度プルリクを作る必要はありません。)

2021-11-17 09:50 UTC, igamasayuki commented on src/types/employee.ts
> +  get fixHireDate(): string {
fixというのは修正という意味で、今回は日付をフォーマットするため
formatHireDate()の方がわかりやすいです。
修正をお願いします。

2021-11-18 00:05 UTC, koda-momo commented on src/types/employee.ts
> +  get fixHireDate(): string {
ご教示頂きありがとうございます、承知しました。

2021-11-18 01:52 UTC, igamasayuki approved these changes
とてもわかりやすくなったと思います。
承認します。

2021-11-18 01:52 UTC, merged